<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2014.1.6
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Contact Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'email' => array(
		'from' => 'jusharvey@gmail.com',
		'to' => 'jusharvey@gmail.com'
	),
	'fields' => array(
		'custom_U658' => array(
			'type' => 'string',
			'label' => 'Custom:',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Custom:\' is required.'
			)
		),
		'Email' => array(
			'type' => 'email',
			'label' => 'Custom:',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Custom:\' is required.',
				'format' => 'Field \'Custom:\' has an invalid email.'
			)
		),
		'custom_U653' => array(
			'type' => 'string',
			'label' => 'Custom:',
			'required' => false,
			'errors' => array(
			)
		)
	)
);

process_form($form);
?>
